App\TiendaOnlineBundle\Entity\Categoria:
    type: entity
    table: categoria
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 45
            fixed: false
            nullable: false
        descripcion:
            type: string
            length: 150
            fixed: false
            nullable: true
        borrado:
            type: integer
            length: 1
            fixed: true
            nullable: true
        created_at:
            type: datetime
            nullable: false
        updated_at:
            type: datetime
            nullable: false

        slug:
          type: string
          length: 128
          gedmo:
            slug:
              separator: _
              style: camel
              fields:
                - nombre


    oneToMany:
        productos:
          targetEntity: Producto
          mappedBy: categoria
          cascade: [ "persist" ]

    lifecycleCallbacks:
        prePersist: [preInsertCategoria]
        preUpdate: [preUpdateCategoria]
