App\TiendaOnlineBundle\Entity\Institucion:
    type: entity
    table: institucion
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 45
            fixed: false
            nullable: false
        descripcion:
            type: string
            length: 150
            fixed: false
            nullable: true
        borrado:
            type: integer
            length: 1
            fixed: true
            nullable: true
        created_at:
            type: datetime
            nullable: false
            gedmo:
              timestampable:
                on: create
        updated_at:
            type: datetime
            nullable: false
            gedmo:
              timestampable:
                on: update            
            
    oneToMany:
        cursos:
          targetEntity: Lista
          mappedBy: institucion
          cascade: [ "persist" ]

    lifecycleCallbacks:
        prePersist: [preInsert]
        preUpdate: [preUpdate]
