App\TiendaOnlineBundle\Entity\Lista:
    type: entity
    table: lista
    fields:
        id:
            id: true
            type: integer
            unsigned: false
            nullable: false
            generator:
                strategy: IDENTITY
        nombre:
            type: string
            length: 45
            fixed: false
            nullable: false
        descripcion:
            type: string
            length: 150
            fixed: false
            nullable: true
        borrado:
            type: integer
            length: 1
            fixed: true
            nullable: true
        created_at:
            type: datetime
            nullable: false
        updated_at:
            type: datetime
            nullable: false
    manyToOne:

      institucion:
        targetEntity: Institucion
        inversedBy: cursos
        joinColumn:
          name: institucion_id
          referencedColumnName: id


    oneToMany:
        detalles:
          targetEntity: DetalleLista
          mappedBy: lista
          cascade: [ "persist" ]



    lifecycleCallbacks:
        prePersist: [preInsert]
        preUpdate: [preUpdate]
